application:
  config:
    back-end:
      api-base-path: "/v1/**"
      server-base-path: "http://localhost:8080"
    front-end:
      first-angular-app:
        resource-handler-path: "/app1/**"
        resource-locations:
          - "classpath:/static/first-angular-app/"
        index-location: "/static/first-angular-app/index.html"
        view-controller: "/app1"
        view-name: "/app1/index.html"
      second-angular-app:
        resource-handler-path: "/app2/**"
        resource-locations:
          - "classpath:/static/second-angular-app/"
        index-location: "/static/second-angular-app/index.html"
        view-controller: "/app2"
        view-name: "/app2/index.html"