# config datasource for Jpa and Jdbc

application:
  server-base-url: "http://localhost:8080"
  get-file-api: "/v1/files/"

spring:
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/storage?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        generate_statistics: true
