
application:
  quartz:
    time-zone: Asia/Ho_Chi_Minh

# config datasource for Jpa and Jdbc
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/quartz?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
    open-in-view: true
#    properties:
#      hibernate:
#        generate_statistics: true
  flyway:
    enabled: true
    baselineOnMigrate: true
    driverClassName: ${spring.datasource.driverClassName}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
  quartz:
    job-store-type: jdbc
    properties:
      org.quartz.jobStore:
        driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate